USE TableRelations

--START
CREATE TABLE Cities(
	CityID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Customers(
	CustomerID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Birthday DATE NOT NULL,
	CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
	OrderID INT PRIMARY KEY NOT NULL,
	CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE ItemTypes(
	ItemTypeID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(50)
)

CREATE TABLE Items(
	ItemID INT PRIMARY KEY NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems(
	OrderID INT,
	ItemID INT,

	CONSTRAINT PK_OrderID_ItemID
	PRIMARY KEY (OrderID, ItemID),

	CONSTRAINT FK_OrderID
	FOREIGN KEY (OrderID)
	REFERENCES Orders(OrderID),

	CONSTRAINT FK_ItemID
	FOREIGN KEY (ItemID)
	REFERENCES Items(ItemID)
)










